//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanProjeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public Nullable<int> Daire { get; set; }
        public string Oturan { get; set; }
        public string gsm { get; set; }
        public string Bakiye { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
